#!/bin/bash

SeedRegion=$1
#subj=$2
#run=$3

script_dir="/gpfs/data/helab/wuy19/scripts/GLM"
data_dir="/gpfs/data/helab/wuy19/HLTP_fMRI/SUBNUM/BLOCKNUM"
cd $script_dir

#create batch script for each subject and run separately
for subj in 01 04 05 07 08 09 11 13 15 16 18 19 20 22 25 26 29 30 31 32 33 34 35 37 38;do

	SUBDIR=/gpfs/data/helab/wuy19/HLTP_fMRI/sub$subj
	. $SUBDIR/sub_params
	for run in $good_blocks; do

		block_dir=$SUBDIR/block${run}
		
		if [ $subj == 04 ] && [ $run == 1 ]
		then
			n_TRs=220
		elif [ $subj == 20 ]  && [ $run == 11 ]
		then
			n_TRs=182
		else
			n_TRs=227
		fi
		
		cp $script_dir/High_VS_Low_Motor_CSFWM_RunFSLFeat $script_dir/GLM_sub${subj}_block${run}
		sed -i -e "s#SUBNUM#sub${subj}#g" $script_dir/GLM_sub${subj}_block${run}
		sed -i -e "s#BLOCKNUM#block${run}#g" $script_dir/GLM_sub${subj}_block${run}
		
		cp $script_dir/High_VS_Low_Motor_CSFWM_template.fsf $script_dir/High_vs_Low_Motor_CSFWM_sub${subj}_block${run}_design.fsf
		sed -i -e "s#BLOCKDIR#${block_dir}#g" $script_dir/High_vs_Low_Motor_CSFWM_sub${subj}_block${run}_design.fsf
		sed -i -e "s#SEED#${SeedRegion}#g" $script_dir/High_vs_Low_Motor_CSFWM_sub${subj}_block${run}_design.fsf
		sed -i -e "s#n_TRs#${n_TRs}#g" $script_dir/High_vs_Low_Motor_CSFWM_sub${subj}_block${run}_design.fsf
		
		sbatch ${script_dir}/GLM_sub${subj}_block${run} 			
	done	
done

