#!/bin/bash

# This script creates a list of HPC jobs and submits it to SLURM job scheduler  
# Each job involves performing a GLM for a given run of a given subject, which will subsequently used for category decoding analysis.  
# Each job create a GLM design file in .fsf format and passes it through *_RunFSLFeat to perform GLM as implemented in FSL feat.
# The script requires a GLM design in .fsf format, sub_params file, and a seed region as input arguments.

# Input: Seed region for GLM analysis

SeedRegion=$1

# Set the directory path
script_dir="/gpfs/home/wuy19/scripts/GLM"
data_dir="/gpfs/home/wuy19/HLTP_fMRI/SUBNUM/BLOCKNUM"


# Navigate to script directory
cd $script_dir

# Iterate through subjects
for subj in 01 04 05 07 08 09 11 13 15 16 18 19 20 22 25 26 29 30 31 32 33 34 35 37 38;do

	SUBDIR=/gpfs/home/wuy19/HLTP_fMRI/sub$subj
	. $SUBDIR/sub_params

	# Iterate through runs for each subject
	for run in $good_blocks; do
		block_dir=$SUBDIR/block${run}
		
		# Determine the number of TRs (Time Repetitions) based on subject and run
		if [ $subj == 04 ] && [ $run == 1 ]
		then
			n_TRs=220
		elif [ $subj == 20 ]  && [ $run == 11 ]
		then
			n_TRs=182
		else
			n_TRs=227
		fi
		
		# Replace keywords in the RunFSLFeat file with subject-specific information
		cp $script_dir/PreSeeds_RunFSLFeat $script_dir/GLM_sub${subj}_block${run}
		sed -i -e "s#SUBNUM#sub${subj}#g" $script_dir/GLM_sub${subj}_block${run}
		sed -i -e "s#BLOCKNUM#block${run}#g" $script_dir/GLM_sub${subj}_block${run}
		
		# Replace keywords in the template file with subject-specific information
		cp $script_dir/PreSeeds_GLM_template.fsf $script_dir/PreSeeds_GLM_sub${subj}_block${run}_design.fsf
		sed -i -e "s#BLOCKDIR#${block_dir}#g" $script_dir/PreSeeds_GLM_sub${subj}_block${run}_design.fsf
		sed -i -e "s#SEED#${SeedRegion}#g" $script_dir/PreSeeds_GLM_sub${subj}_block${run}_design.fsf
		sed -i -e "s#n_TRs#${n_TRs}#g" $script_dir/PreSeeds_GLM_sub${subj}_block${run}_design.fsf		
		
		# Submit the RunFSLFeat for each subjet asnd run 
		sbatch ${script_dir}/GLM_sub${subj}_block${run} 			
	done	
done