#!/bin/bash
#SBATCH --job-name=GLM_SUBNUM_BLOCKNUM
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=yuanhao.wu@nyulangone.org
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --time=24:00:00
#SBATCH --mem-per-cpu=32G



#  #SBATCH --output=GLM_SUBNUM_BLOCKNUM_%j.log

script_dir="/gpfs/data/helab/wuy19/scripts/GLM"
data_dir="/gpfs/data/helab/wuy19/HLTP_fMRI/SUBNUM/BLOCKNUM"
cd "/gpfs/data/helab/wuy19/scripts/GLM"
module load fsl/6.0.0
echo "####################################################################"	
echo "   Model specification and estimation for BLOCKNUM in SUBNUM        "

echo "####################################################################"
feat ./High_vs_Low_Motor_CSFWM_SUBNUM_BLOCKNUM_design.fsf
rm ./High_vs_Low_Motor_CSFWM_SUBNUM_BLOCKNUM_design.fsf
rm ./GLM_SUBNUM_BLOCKNUM
#rm $data_dir/denoised_data.nii.gz
#rm -r $data_dir/evs

 

